# Generated by Django 4.2.13 on 2024-05-12 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('secondName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dateOfBirth', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
