# Generated by Django 4.2.13 on 2024-05-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alshifa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
