# Generated by Django 4.2.13 on 2024-05-12 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alshifa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
