# Generated by Django 4.2.13 on 2024-05-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alshifa', '0003_services_doctor_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alshifa.services'),
        ),
    ]
