# Generated by Django 4.2.13 on 2024-05-13 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alshifa', '0005_services_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/media/'),
            preserve_default=False,
        ),
    ]
